version: "3.7"

networks:
  rotten-potatoes-ms-net:
    driver: bridge

services:

  rotten-potatoes-ms:
    image: ferrarijose/rotten-potatoes-ms:${TAG_ROTTEN}
    ports:
      - 5000:5000
    networks:
      - rotten-potatoes-ms-net
    depends_on:
      - movie
      - review
    environment:
      MOVIE_SERVICE_URI: ${MOVIE_SERVICE_URI}
      REVIEW_SERVICE_URI: ${REVIEW_SERVICE_URI}
  
  movie:
    image: ferrarijose/movie:${TAG_MOVIE}
    ports:
      - 8081:80
    networks:
      - rotten-potatoes-ms-net
    depends_on:
      - mongo
    environment:
      MONGODB_URI: ${MONGODB_URI}
  
  review:
    image: ferrarijose/review:${TAG_REVIEW}
    ports:
      - 8082:80
    networks:
      - rotten-potatoes-ms-net
    depends_on:
      - postgres
    environment:
      ConnectionStrings__MyConnection: ${CONNECTIONSTRING_PG}
  
  mongo:
    image: mongo:${TAG_MONGO}
    restart: always
    ports:
      - 27017:27017
    networks:
      - rotten-potatoes-ms-net
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    volumes:
      - mongo_rotten_potatoes_ms_vol:${MONGODB_VOLUME}
  
  postgres:
    image: postgres:${TAG_PG}
    ports:
      - 5432:5432
    networks:
      - rotten-potatoes-ms-net
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_rotten_potatoes_ms_vol:${PG_VOLUME}  

volumes: 
  mongo_rotten_potatoes_ms_vol:
  postgres_rotten_potatoes_ms_vol: